language: php

env:
    - SYMFONY_VERSION="2.2.*"
    - SYMFONY_VERSION="2.3.*"
    - SYMFONY_VERSION="2.4.*"
    - SYMFONY_VERSION="2.5.*"

# 'symfony/templating' is a hack for https://github.com/symfony/symfony/pull/8280 resulting in method access mismatch
# We only install Mongo to ensure the container compiles properly with multiple db-drivers
before_script:
    - echo "extension=mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    - COMPOSER_ROOT_VERSION=dev-master
    - composer self-update
    - composer require symfony/symfony:${SYMFONY_VERSION} --no-update
    - composer install --dev

php:
  - 5.3
  - 5.4
  - 5.5

script: phpunit --configuration phpunit.xml.dist --exclude-group "" --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
